<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Helper;

class BjHands extends Model
{

    protected $guarded = [
        'id',
        'created_at',
        'updated_at',
    ];

    protected $casts = [
        'p_hand' => 'array',
        'd_hand' => 'array',
    ];

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::creating(function (self $hand) {
            if (!$hand->p_hand) {
                $hand->p_hand = [];
            }
            if (!$hand->d_hand) {
                $hand->d_hand = [];
            }
        });
    }


    public function bj_game()
    {
        return $this->belongsTo('App\BjGame','bjgame_id','id');
    }

    public function finishGame()
    {
        $p_hand_point=Helper::calculateHand($this->p_hand);
        $d_hand_point=Helper::calculateHand($this->d_hand);
        if($p_hand_point==21&&count($this->p_hand)==2&&$d_hand_point!=21)
        {
            $this->state='win';
            $this->bj_game->userWin();
            Helper::setFlashData('blackjack');
        }
        else if($p_hand_point > 21)
        {
            $this->state='lose';
            $this->bj_game->dealerWin();
            Helper::setFlashData('user_busted');
        }
        elseif ($d_hand_point>21)
        {
            $this->state='win';
            $this->bj_game->userWin();
            Helper::setFlashData('dealer_busted');
        }
        else
        {
            if($p_hand_point > $d_hand_point)
            {
                $this->state='win';
                $this->bj_game->userWin();
                Helper::setFlashData('user_wins');
            }
            elseif($p_hand_point < $d_hand_point)
            {
                $this->state='lose';
                $this->bj_game->dealerWin();
                Helper::setFlashData('dealer_wins');
            }
            else
            {
                $this->state='draw';
                Helper::setFlashData('draw');
            }
        }
        $this->player_point=$p_hand_point;
        $this->dealer_point=$d_hand_point;
        $this->save();
    }
}
